/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.bibparser.node;

import java.util.*;
import net.sourceforge.texlipse.bibparser.analysis.*;

public final class ABibtaskBibEntry extends PBibEntry
{
    private TTaskcomment _taskcomment_;

    public ABibtaskBibEntry()
    {
    }

    public ABibtaskBibEntry(
        TTaskcomment _taskcomment_)
    {
        setTaskcomment(_taskcomment_);

    }
    public Object clone()
    {
        return new ABibtaskBibEntry(
            (TTaskcomment) cloneNode(_taskcomment_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABibtaskBibEntry(this);
    }

    public TTaskcomment getTaskcomment()
    {
        return _taskcomment_;
    }

    public void setTaskcomment(TTaskcomment node)
    {
        if(_taskcomment_ != null)
        {
            _taskcomment_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _taskcomment_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_taskcomment_);
    }

    void removeChild(Node child)
    {
        if(_taskcomment_ == child)
        {
            _taskcomment_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_taskcomment_ == oldChild)
        {
            setTaskcomment((TTaskcomment) newChild);
            return;
        }

    }
}
