/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.bibparser.node;

import java.util.*;
import net.sourceforge.texlipse.bibparser.analysis.*;

public final class AConcat extends PConcat
{
    private PValOrSid _valOrSid_;

    public AConcat()
    {
    }

    public AConcat(
        PValOrSid _valOrSid_)
    {
        setValOrSid(_valOrSid_);

    }
    public Object clone()
    {
        return new AConcat(
            (PValOrSid) cloneNode(_valOrSid_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConcat(this);
    }

    public PValOrSid getValOrSid()
    {
        return _valOrSid_;
    }

    public void setValOrSid(PValOrSid node)
    {
        if(_valOrSid_ != null)
        {
            _valOrSid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _valOrSid_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_valOrSid_);
    }

    void removeChild(Node child)
    {
        if(_valOrSid_ == child)
        {
            _valOrSid_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_valOrSid_ == oldChild)
        {
            setValOrSid((PValOrSid) newChild);
            return;
        }

    }
}
