/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.bibparser.node;

import java.util.*;
import net.sourceforge.texlipse.bibparser.analysis.*;

public final class AEntryDef extends PEntryDef
{
    private TEntryName _entryName_;

    public AEntryDef()
    {
    }

    public AEntryDef(
        TEntryName _entryName_)
    {
        setEntryName(_entryName_);

    }
    public Object clone()
    {
        return new AEntryDef(
            (TEntryName) cloneNode(_entryName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEntryDef(this);
    }

    public TEntryName getEntryName()
    {
        return _entryName_;
    }

    public void setEntryName(TEntryName node)
    {
        if(_entryName_ != null)
        {
            _entryName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _entryName_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_entryName_);
    }

    void removeChild(Node child)
    {
        if(_entryName_ == child)
        {
            _entryName_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_entryName_ == oldChild)
        {
            setEntryName((TEntryName) newChild);
            return;
        }

    }
}
