/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.bibparser.node;

import java.util.*;
import net.sourceforge.texlipse.bibparser.analysis.*;

public final class AEntryparenEntry extends PEntry
{
    private PEntryDef _entryDef_;
    private TIdentifier _identifier_;
    private final LinkedList _keyvalDecl_ = new TypedLinkedList(new KeyvalDecl_Cast());

    public AEntryparenEntry()
    {
    }

    public AEntryparenEntry(
        PEntryDef _entryDef_,
        TIdentifier _identifier_,
        List _keyvalDecl_)
    {
        setEntryDef(_entryDef_);

        setIdentifier(_identifier_);

        {
            this._keyvalDecl_.clear();
            this._keyvalDecl_.addAll(_keyvalDecl_);
        }

    }
    public Object clone()
    {
        return new AEntryparenEntry(
            (PEntryDef) cloneNode(_entryDef_),
            (TIdentifier) cloneNode(_identifier_),
            cloneList(_keyvalDecl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEntryparenEntry(this);
    }

    public PEntryDef getEntryDef()
    {
        return _entryDef_;
    }

    public void setEntryDef(PEntryDef node)
    {
        if(_entryDef_ != null)
        {
            _entryDef_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _entryDef_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public LinkedList getKeyvalDecl()
    {
        return _keyvalDecl_;
    }

    public void setKeyvalDecl(List list)
    {
        _keyvalDecl_.clear();
        _keyvalDecl_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_entryDef_)
            + toString(_identifier_)
            + toString(_keyvalDecl_);
    }

    void removeChild(Node child)
    {
        if(_entryDef_ == child)
        {
            _entryDef_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_keyvalDecl_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_entryDef_ == oldChild)
        {
            setEntryDef((PEntryDef) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator i = _keyvalDecl_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class KeyvalDecl_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PKeyvalDecl node = (PKeyvalDecl) o;

            if((node.parent() != null) &&
                (node.parent() != AEntryparenEntry.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AEntryparenEntry.this))
            {
                node.parent(AEntryparenEntry.this);
            }

            return node;
        }
    }
}
