/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.bibparser.node;

import net.sourceforge.texlipse.bibparser.analysis.*;

public final class Start extends Node
{
    private PBibtex _pBibtex_;
    private EOF _eof_;

    public Start()
    {
    }

    public Start(
        PBibtex _pBibtex_,
        EOF _eof_)
    {
        setPBibtex(_pBibtex_);
        setEOF(_eof_);
    }

    public Object clone()
    {
        return new Start(
            (PBibtex) cloneNode(_pBibtex_),
            (EOF) cloneNode(_eof_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PBibtex getPBibtex()
    {
        return _pBibtex_;
    }

    public void setPBibtex(PBibtex node)
    {
        if(_pBibtex_ != null)
        {
            _pBibtex_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pBibtex_ = node;
    }

    public EOF getEOF()
    {
        return _eof_;
    }

    public void setEOF(EOF node)
    {
        if(_eof_ != null)
        {
            _eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eof_ = node;
    }

    void removeChild(Node child)
    {
        if(_pBibtex_ == child)
        {
            _pBibtex_ = null;
            return;
        }

        if(_eof_ == child)
        {
            _eof_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pBibtex_ == oldChild)
        {
            setPBibtex((PBibtex) newChild);
            return;
        }

        if(_eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }
    }

    public String toString()
    {
        return "" +
            toString(_pBibtex_) +
            toString(_eof_);
    }
}
