/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.texparser.node;

import net.sourceforge.texlipse.texparser.analysis.*;

public final class TCchapter extends Token
{
    public TCchapter()
    {
        super.setText("\\chapter");
    }

    public TCchapter(int line, int pos)
    {
        super.setText("\\chapter");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TCchapter(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCchapter(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TCchapter text.");
    }
}
