/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.texparser.node;

import net.sourceforge.texlipse.texparser.analysis.Analysis;

public final class TCend extends Token
{
    public TCend()
    {
        super.setText("\\end");
    }

    public TCend(int line, int pos)
    {
        super.setText("\\end");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TCend(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCend(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TCend text.");
    }
}
