/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.texparser.node;

import net.sourceforge.texlipse.texparser.analysis.*;

public final class TCinput extends Token
{
    public TCinput()
    {
        super.setText("\\input");
    }

    public TCinput(int line, int pos)
    {
        super.setText("\\input");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TCinput(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCinput(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TCinput text.");
    }
}
