/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.texparser.node;

import net.sourceforge.texlipse.texparser.analysis.*;

public final class TCrenew extends Token
{
    public TCrenew()
    {
        super.setText("\\renewcommand");
    }

    public TCrenew(int line, int pos)
    {
        super.setText("\\renewcommand");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TCrenew(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCrenew(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TCrenew text.");
    }
}
