# This workflow will check for Maven projects if the licenses of all (transitive) dependencies are vetted.

name: Eclipse Dash License Tool

on:
  push:
    branches: 
      - 'master'
  pull_request:
    branches: 
     - 'master'
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    uses: eclipse/dash-licenses/.github/workflows/mavenLicenseCheck.yml@master
    with:
      projectId: science.texlipse
    secrets:
      gitlabAPIToken: ${{ secrets.GITLAB_API_TOKEN }}