/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.eclipse.texlipse.texparser.node;

import org.eclipse.texlipse.texparser.analysis.*;

@SuppressWarnings("nls")
public final class TChref extends Token
{
    public TChref()
    {
        super.setText("\\href");
    }

    public TChref(int line, int pos)
    {
        super.setText("\\href");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TChref(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTChref(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TChref text.");
    }
}
