/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.eclipse.texlipse.texparser.node;

import org.eclipse.texlipse.texparser.analysis.*;

@SuppressWarnings("nls")
public final class TCinput extends Token
{
    public TCinput()
    {
        super.setText("\\input");
    }

    public TCinput(int line, int pos)
    {
        super.setText("\\input");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCinput(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCinput(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCinput text.");
    }
}
