/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.bibparser.parser;

import net.sourceforge.texlipse.bibparser.node.*;
import net.sourceforge.texlipse.bibparser.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTEstring(TEstring node)
    {
        index = 0;
    }

    public void caseTScribeComment(TScribeComment node)
    {
        index = 1;
    }

    public void caseTPreamble(TPreamble node)
    {
        index = 2;
    }

    public void caseTEntryName(TEntryName node)
    {
        index = 3;
    }

    public void caseTLBrace(TLBrace node)
    {
        index = 4;
    }

    public void caseTRBrace(TRBrace node)
    {
        index = 5;
    }

    public void caseTBString(TBString node)
    {
        index = 6;
    }

    public void caseTLParen(TLParen node)
    {
        index = 7;
    }

    public void caseTRParen(TRParen node)
    {
        index = 8;
    }

    public void caseTComma(TComma node)
    {
        index = 9;
    }

    public void caseTEquals(TEquals node)
    {
        index = 10;
    }

    public void caseTSharp(TSharp node)
    {
        index = 11;
    }

    public void caseTNumber(TNumber node)
    {
        index = 12;
    }

    public void caseTIdentifier(TIdentifier node)
    {
        index = 13;
    }

    public void caseTQuotec(TQuotec node)
    {
        index = 14;
    }

    public void caseTStringLiteral(TStringLiteral node)
    {
        index = 15;
    }

    public void caseEOF(EOF node)
    {
        index = 16;
    }
}
