/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.texparser.analysis;

import net.sourceforge.texlipse.texparser.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTWhitespace(TWhitespace node);
    void caseTCpart(TCpart node);
    void caseTCchapter(TCchapter node);
    void caseTCsection(TCsection node);
    void caseTCssection(TCssection node);
    void caseTCsssection(TCsssection node);
    void caseTCparagraph(TCparagraph node);
    void caseTCbib(TCbib node);
    void caseTCbibstyle(TCbibstyle node);
    void caseTClabel(TClabel node);
    void caseTCref(TCref node);
    void caseTCcite(TCcite node);
    void caseTCbegin(TCbegin node);
    void caseTCend(TCend node);
    void caseTCinput(TCinput node);
    void caseTCinclude(TCinclude node);
    void caseTCnew(TCnew node);
    void caseTCrenew(TCrenew node);
    void caseTCpackage(TCpackage node);
    void caseTCpindex(TCpindex node);
    void caseTCpbib(TCpbib node);
    void caseTBverbatim(TBverbatim node);
    void caseTEverbatim(TEverbatim node);
    void caseTVtext(TVtext node);
    void caseTCverb(TCverb node);
    void caseTArgument(TArgument node);
    void caseTOptargument(TOptargument node);
    void caseTStar(TStar node);
    void caseTLBrace(TLBrace node);
    void caseTRBrace(TRBrace node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTCword(TCword node);
    void caseTCsymbol(TCsymbol node);
    void caseTCspace(TCspace node);
    void caseTWord(TWord node);
    void caseTSkippedArea(TSkippedArea node);
    void caseTTaskcomment(TTaskcomment node);
    void caseTCommentline(TCommentline node);
    void caseEOF(EOF node);
}
