/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.texparser.analysis;

import net.sourceforge.texlipse.texparser.node.EOF;
import net.sourceforge.texlipse.texparser.node.Node;
import net.sourceforge.texlipse.texparser.node.Switch;
import net.sourceforge.texlipse.texparser.node.TArgument;
import net.sourceforge.texlipse.texparser.node.TBverbatim;
import net.sourceforge.texlipse.texparser.node.TCbegin;
import net.sourceforge.texlipse.texparser.node.TCbib;
import net.sourceforge.texlipse.texparser.node.TCbibstyle;
import net.sourceforge.texlipse.texparser.node.TCchapter;
import net.sourceforge.texlipse.texparser.node.TCcite;
import net.sourceforge.texlipse.texparser.node.TCend;
import net.sourceforge.texlipse.texparser.node.TCinclude;
import net.sourceforge.texlipse.texparser.node.TCinput;
import net.sourceforge.texlipse.texparser.node.TClabel;
import net.sourceforge.texlipse.texparser.node.TCnew;
import net.sourceforge.texlipse.texparser.node.TCommentline;
import net.sourceforge.texlipse.texparser.node.TCparagraph;
import net.sourceforge.texlipse.texparser.node.TCpart;
import net.sourceforge.texlipse.texparser.node.TCpindex;
import net.sourceforge.texlipse.texparser.node.TCref;
import net.sourceforge.texlipse.texparser.node.TCrenew;
import net.sourceforge.texlipse.texparser.node.TCsection;
import net.sourceforge.texlipse.texparser.node.TCspace;
import net.sourceforge.texlipse.texparser.node.TCssection;
import net.sourceforge.texlipse.texparser.node.TCsssection;
import net.sourceforge.texlipse.texparser.node.TCsymbol;
import net.sourceforge.texlipse.texparser.node.TCverb;
import net.sourceforge.texlipse.texparser.node.TCword;
import net.sourceforge.texlipse.texparser.node.TEverbatim;
import net.sourceforge.texlipse.texparser.node.TLBrace;
import net.sourceforge.texlipse.texparser.node.TLBracket;
import net.sourceforge.texlipse.texparser.node.TOptargument;
import net.sourceforge.texlipse.texparser.node.TRBrace;
import net.sourceforge.texlipse.texparser.node.TRBracket;
import net.sourceforge.texlipse.texparser.node.TStar;
import net.sourceforge.texlipse.texparser.node.TVtext;
import net.sourceforge.texlipse.texparser.node.TWhitespace;
import net.sourceforge.texlipse.texparser.node.TWord;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseTWhitespace(TWhitespace node);
    void caseTCpart(TCpart node);
    void caseTCchapter(TCchapter node);
    void caseTCsection(TCsection node);
    void caseTCssection(TCssection node);
    void caseTCsssection(TCsssection node);
    void caseTCparagraph(TCparagraph node);
    void caseTCbib(TCbib node);
    void caseTCbibstyle(TCbibstyle node);
    void caseTClabel(TClabel node);
    void caseTCref(TCref node);
    void caseTCcite(TCcite node);
    void caseTCbegin(TCbegin node);
    void caseTCend(TCend node);
    void caseTCinput(TCinput node);
    void caseTCinclude(TCinclude node);
    void caseTCnew(TCnew node);
    void caseTCrenew(TCrenew node);
    void caseTCpindex(TCpindex node);
    void caseTBverbatim(TBverbatim node);
    void caseTEverbatim(TEverbatim node);
    void caseTVtext(TVtext node);
    void caseTCverb(TCverb node);
    void caseTArgument(TArgument node);
    void caseTOptargument(TOptargument node);
    void caseTStar(TStar node);
    void caseTLBrace(TLBrace node);
    void caseTRBrace(TRBrace node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTCword(TCword node);
    void caseTCsymbol(TCsymbol node);
    void caseTCspace(TCspace node);
    void caseTWord(TWord node);
    void caseTCommentline(TCommentline node);
    void caseEOF(EOF node);
}
