/**
 * Copyright (c) 2004-2017 the TeXlapse team.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_texlipse_DDEClient */

#ifndef _Included_org_eclipse_texlipse_DDEClient
#define _Included_org_eclipse_texlipse_DDEClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_texlipse_DDEClient
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_texlipse_DDEClient_execute
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
