###############################################################################
# Copyright (c) 2024 ArSysOp and others
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Alexander Fedorov (ArSysOp) - initial API and implementation
###############################################################################

name: Eclipse Dash License Tool

on:
  push:
    branches: 
      - 'master'
      - 'R*'
  pull_request:
    branches: 
     - 'master'
     - 'R*'
  issue_comment:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.0
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: License check
      run: | 
        mvn -U -V -e -B -ntp org.eclipse.dash:license-tool-plugin:license-check -Ddash.fail=false --file pom.xml